import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Container from "@/components/container";
import { Providers } from "../components/provider"; 

import './global.css'


const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wefit Test - Diandra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={openSans.className}>
            <Providers>
              <Container>{children}</Container>
            </Providers>
      </body>
    </html>
  );
}

